export interface IPostFormModel {
  Rubrik:string,
  UnderRubrik:string,
  Innehall:string,
  Arrangemangtyp:string,
  Konstform:[],
  Konstform2:string,
  Konstform3:string,
  KontaktId:string,
  Kontaktfornamn:string,
  KontaktEfternamn:string,
  KontaktTelefon:string,
  KontaktEpost:string,
  Faktalist: any,
  MainImage: any,
  Utovare:string,
  UtovarID:string,
  Organisation: string,
  Fornamn:string,
  Efternamn:string,
  Telefon:string,
  Adress:string,
  Postnr:string,
  Ort:string,
  Epost:string,
  Kommun:string,
  Weburl:string,
}
